---
title: "Primary Metal Exposure"



---

 

```{r}
library(tidyverse)

primetalraw <- read_csv("C:/Users/Admin/Downloads/top 100 financings closed q1 june 2018 - Sheet5.csv")

glimpse(primetalraw)

```


Using Cookbook faceted on 46 from baseball. 


```{r}


primetalraw20m <- primetalraw %>% filter(FinalAmountUSD>15000000)


ggplot(primetalraw20m, aes(x=FinalAmountUSD, y=Company)) +
 geom_segment(aes(yend=Company), xend=0, colour="grey50") +
 geom_point(size=3, aes(colour=PrimaryMetalExposure)) +
# scale_colour_brewer(palette="Set1", limits=c("NL","AL")) +
 theme_bw() +
 theme(panel.grid.major.y = element_blank()) +
 facet_grid(PrimaryMetalExposure ~ ., scales="free_y", space="free_y")



```


So above doesn't look good. Let's just do a bar chart coloured. 


```{r}


primetalraw20m <- primetalraw %>% filter(FinalAmountUSD>15000000)


ggplot(primetalraw, aes(x=FinalAmountUSD, y=reorder(Company,FinalAmountUSD))) +
 geom_segment(aes(yend=Company), xend=0, colour="grey50") +
 geom_point(size=3, aes(colour=PrimaryMetalExposure)) +
# scale_colour_brewer(palette="Set1", limits=c("NL","AL")) +
 theme_bw() +
 theme(panel.grid.major.y = element_blank()) 


```



```{r}


primetalraw20m <- primetalraw %>% filter(FinalAmountUSD>15000000)


ggplot(primetalraw20m, aes(x=FinalAmountUSD, y=Company)) +
 geom_segment(aes(yend=Company), xend=0, colour="grey50") +
 geom_point(size=3, aes(colour=PrimaryMetalExposure)) +
# scale_colour_brewer(palette="Set1", limits=c("NL","AL")) +
 theme_bw() +
 theme(panel.grid.major.y = element_blank()) +
 facet_wrap(~PrimaryMetalExposure,scales="free_y")



```



Try as a bar chart

```{r}

library(showtext)
library(extrafont)
library(scales)

primetalraw15 <- primetalraw %>% filter(FinalAmountUSD>10000000)

t <- ggplot(primetalraw15, aes(y=FinalAmountUSD, x=reorder(Company,FinalAmountUSD))) +
  geom_bar(stat="identity")+
  geom_text(aes(label=scales::dollar(FinalAmountUSD)), hjust=-.1)+
  coord_flip()+
  theme_minimal(base_size=16, base_family="Montserrat")+
  scale_y_continuous(limits=c(0,500000000),labels = scales::dollar)+
  scale_fill_manual(values=c('#a6cee3','#1f78b4','#b2df8a','#ff7f00','#fb9a99','#e31a1c','#fdbf6f','#33a02c','#cab2d6','#6a3d9a','#ffff99'))

t

ggsave("font_ggplot22.pdf", plot=t, width=300, height=300, units="mm")




```



Let's look at the data by commodity raised. 

```{r}


byprimary <- primetalraw %>% filter(FinalAmountUSD>10000000) %>% group_by(PrimaryMetalExposure) %>% summarise(Total = sum(FinalAmountUSD))
byprimary


```


And chart


```{r}



z <- ggplot(byprimary, aes(y=Total, x=reorder(PrimaryMetalExposure,Total))) +
  geom_bar(stat="identity")+
  geom_text(aes(label=scales::dollar(Total)), hjust=-.1, family="Montserrat")+
  coord_flip()+
  theme_minimal(base_size=14, base_family="Montserrat")+
  theme(plot.title = element_text(size = rel(2.5), family="Zilla Slab Light"))+
  scale_y_continuous(limits=c(0,1000000000),labels = scales::dollar, breaks=c(0,250000000,500000000,750000000))+
  labs(title="Financings by Commodity Q1 2018", subtitle="Total Closed Financings for Companies by Their Primary Commodity. Amounts over $10M.",x="", y="", caption="Data from Mining Intelligence")

z

ggsave("financecommo15.pdf", plot=z, width=250, height=200, units="mm")



```


Bar chart with proper formatting. 


```{r}

library(showtext)
library(extrafont)
library(scales)

primetalraw15 <- primetalraw %>% filter(FinalAmountUSD>10000000)

t <- ggplot(primetalraw15, aes(y=FinalAmountUSD, x=reorder(Company,FinalAmountUSD))) +
  geom_bar(stat="identity")+
  geom_text(aes(label=scales::dollar(FinalAmountUSD)), hjust=-.1)+
  coord_flip()+
  theme_minimal(base_size=14, base_family="Montserrat")+
  theme(plot.title = element_text(size = rel(2.5), family="Zilla Slab Light"))+
  scale_y_continuous(limits=c(0,500000000),labels = scales::dollar, breaks=c(0,200000000,400000000)) +
  labs(title="Top Financings in Q1 2018", subtitle="Closed Financings over $10M", x="", y="")
t

ggsave("topfinance15.pdf", plot=t, width=250, height=200, units="mm")




```

